{
    "postgres": {
        "connection_string": "postgres://postgres:postgres@127.0.0.1:5432/skgbot-test",
        "connection_string_reset": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
        "host": null,
        "pool_min": 2,
        "pool_max": 4,
        "migrations": {
            "tablename": "knex_migrations"
        }
    }
}
